Todo-aspnetmvc-ui/Controllers/ListController.cs
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Todo_aspnetmvc_ui.Models.ViewModels;
using Todo_domain_entities;
using Todo_services.Interfaces;

namespace Todo_aspnetmvc_ui.Controllers
{
    /// <summary>
    /// List controller.
    /// </summary>
    [Authorize]
    public class ListController : Controller
    {
        private readonly IToDoListSevices listServices;
        private readonly ILogger<ListController> logger;

        /// <summary>
        /// Initializes a new instance of the <see cref="ListController"/> class.
        /// </summary>
        /// <param name="listServices">list services.</param>
        /// <param name="logger">logger.</param>
        public ListController(IToDoListSevices listServices, ILogger<ListController> logger)
        {
            this.listServices = listServices;
            this.logger = logger;
        }

        /// <summary>
        /// UI to create the ToDoList.
        /// </summary>
        /// <returns>The view to create the ToDoList.</returns>
        public IActionResult Create()
        {
            var listMod = new ListDataInputViewModel
            {
                TodoList = new ToDoList(),
                ReturnUrl = this.GetRefer(),
            };

            this.logger.LogInformation($"The form to create a new todo list was shown to user {this.UserId()} at {DateTime.Now}");

            return this.View(listMod);
        }

        /// <summary>
        /// create new list.
        /// </summary>
        /// <param name="list">new ToDoList.</param>
        /// <returns>tasks list.</returns>
        [HttpPost]
        public async Task<IActionResult> Create(ToDoList list)
        {
            long newId = 0;

            if (!this.ModelState.IsValid)
            {
                return this.View(list);
            }

            list.UserId = this.UserId();

            try
            {
                newId = await this.listServices.AddListAsync(list);
                this.logger.LogInformation($"New list <{list.Title}> added {DateTime.Now} by user {list.UserId}");
            }
            catch (Exception ex)
            {
                this.logger.LogError(ex, $"{ex.Message}. An error occurred while trying to create a new todo list. Passed values: UserId <{list.UserId}>, Title <{list.Title}>, Description <{list.Description}>, Hide <{list.Hide}>");
                return this.Redirect("/Error.html");
            }

            return this.RedirectToAction("Tasks", "Task", new { id = newId });
        }

        /// <summary>
        /// UI to edit the ToDoList.
        /// </summary>
        /// <param name="id">list id.</param>
        /// <returns>The view to edit the ToDoList.</returns>
        public async Task<ActionResult> Edit(long id)
        {
            await this.IfNotCurrentUserExeptionAsync(idList: id);

            var list = (await this.listServices.GetAllListsAsync()).FirstOrDefault(x => x.Id == id);

            var listMod = new ListDataInputViewModel
            {
                TodoList = list,
                ReturnUrl = this.GetRefer(),
            };

            this.logger.LogInformation($"The form to edit todo list {id} was shown to user {this.UserId()} at {DateTime.Now}");

            return this.View(listMod);
        }

        /// <summary>
        /// Save list.
        /// </summary>
        /// <param name="id">list id.</param>
        /// <param name="list">edited list.</param>
        /// <param name="returnUrl">return Url.</param>
        /// <returns>All tasks in list.</returns>
        [HttpPost]
        public async Task<ActionResult> Edit(long id, ToDoList list, string returnUrl)
        {
            await this.IfNotCurrentUserExeptionAsync(idList: id);

            if (!this.ModelState.IsValid)
            {
                return this.View(list);
            }

            try
            {
                await this.listServices.UpdateListAsync(list);
                this.logger.LogInformation($"List {id} edited at {DateTime.Now} by user {this.UserId()}");
            }
            catch (Exception ex)
            {
                this.logger.LogError(ex, $"{ex.Message}. An error occurred while trying to edit todo list {id}. Passed values: UserId <{list.UserId}>, Title <{list.Title}>, Description <{list.Description}>, Hide <{list.Hide}>");
                return this.Redirect("/Error.html");
            }

            return this.Redirect(returnUrl);
        }

        /// <summary>
        /// Hide or show a list in an application's list view.
        /// </summary>
        /// <param name="id">list id.</param>
        /// <returns>lists view.</returns>
        public async Task<ActionResult> ChangeVisibility(long id)
        {
            await this.IfNotCurrentUserExeptionAsync(idList: id);

            try
            {
                await this.listServices.ChangeVisibilityAsync(id);

                this.logger.LogInformation($"Visibility of list {id} changed at {DateTime.Now} by user {this.UserId()}");
            }
            catch (Exception ex)
            {
                this.logger.LogError(ex, $"{ex.Message}. An error occurred while trying to change visibility of todo list {id} by user {this.UserId()}.");
                return this.Redirect("/Error.html");
            }

            return this.Redirect(this.GetRefer());
        }

        /// <summary>
        /// Create a copy of the list.
        /// </summary>
        /// <param name="id">list id.</param>
        /// <returns>All list.</returns>
        public async Task<ActionResult> Copy(long id)
        {
            await this.IfNotCurrentUserExeptionAsync(idList: id);

            long newId = 0;

            try
            {
                newId = await this.listServices.CopyListAsync(id);
                this.logger.LogInformation($"A copy of the todo list {id} has been created. New to-do list ID: {newId}. Done on {DateTime.Now} by user {this.UserId()}");
            }
            catch (Exception ex)
            {
                this.logger.LogError(ex, $"{ex.Message}. An error occurred while trying to create a copy of todo list {id}.");
                return this.Redirect("/Error.html");
            }

            return this.RedirectToAction("Tasks", "Task", new { id = newId });
        }

        /// <summary>
        /// Confirmation before deletion.
        /// </summary>
        /// <param name="id">list id.</param>
        /// <returns>Confirmation view.</returns>
        [HttpGet]
        public async Task<ActionResult> Delete(long id)
        {
            await this.IfNotCurrentUserExeptionAsync(idList: id);
            ToDoList? list = (await this.listServices.GetAllListsAsync()).FirstOrDefault(x => x.Id == id);

            var listMod = new ListDataInputViewModel
            {
                TodoList = list,
                ReturnUrl = this.GetRefer(),
            };

            this.logger.LogInformation($"The form to delete todo list {id} was shown to user {this.UserId()} at {DateTime.Now}");

            return this.View(listMod);
        }

        /// <summary>
        /// Delete list.
        /// </summary>
        /// <param name="toDoList">list.</param>
        /// <returns>All tasks in list.</returns>
        [HttpPost]
        public async Task<ActionResult> Delete(ToDoList toDoList)
        {
            var idList = toDoList.Id;

            await this.IfNotCurrentUserExeptionAsync(idList);

            try
            {
                await this.listServices.DeleteListAsync(toDoList.Id);
                this.logger.LogInformation($"Todo list {idList} has been deleted at {DateTime.Now} by user {this.UserId()}.");
            }
            catch (Exception ex)
            {
                this.logger.LogError(ex, $"{ex.Message}. An error occurred while trying to delete todo list {idList}.");
                return this.Redirect("/Error.html");
            }

            return this.RedirectToAction("Index", "Home");
        }

        private string UserId()
        {
            return this.User.FindFirstValue(ClaimTypes.NameIdentifier);
        }

        private async Task IfNotCurrentUserExeptionAsync(long idList)
        {
            var userId = this.UserId();

            if (!(await this.listServices.GetAllListsAsync()).Any(x => x.Id == idList && x.UserId == userId))
            {
                this.logger.LogWarning($"User {this.UserId()} tryed to get access to strange todo list {idList}.");

                throw new InvalidOperationException("not a valid user!!!");
            }
        }

        private string GetRefer()
        {
            var result = this.Request.Headers["Referer"].ToString();
            if (string.IsNullOrEmpty(result))
            {
                return "/";
            }

            return result;
        }
    }
}

Todo-aspnetmvc-ui/ViewComponents/RemainderViewComponent.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Todo_domain_entities;
using Todo_services.Interfaces;

namespace Todo_aspnetmvc_ui.ViewComponents
{
    [ViewComponent]
    public class RemainderViewComponent : ViewComponent
    {
        private readonly IToDoListSevices listServices;
        private readonly IToDoListTaskSevices taskServices;
        private readonly UserManager<IdentityUser> userManager;

        /// <summary>
        /// Initializes a new instance of the <see cref="RemainderViewComponent"/> class.
        /// </summary>
        /// <param name="userManager">userManager.</param>
        /// <param name="listServices">listServices.</param>
        /// <param name="taskServices">taskServices.</param>
        public RemainderViewComponent(UserManager<IdentityUser> userManager, IToDoListSevices listServices, IToDoListTaskSevices taskServices)
        {
            this.listServices = listServices;
            this.taskServices = taskServices;
            this.userManager = userManager;
        }

        /// <summary>
        /// Return number of reminders to the ViewBag.
        /// </summary>
        /// <returns>Number of reminders.</returns>
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var userId = this.userManager.GetUserId(this.UserClaimsPrincipal);

            var tasks = from list in await this.listServices.GetAllListsAsync()
                    where list.UserId == userId
                    join task in await this.taskServices.GetAllTasksAsync()
                    on list.Id equals task.ToDoListId
                    where task.Remind < DateTime.UtcNow && task.Remind > DateTime.Now.AddYears(-100)
                    select task.Id;

            this.ViewBag.reminders = tasks.Count();
            return this.View();
        }
    }
}

Todo-aspnetmvc-ui/ViewComponents/TodoListsViewComponent.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Todo_services.Interfaces;

namespace Todo_aspnetmvc_ui.ViewComponents
{
    [ViewComponent]
    public class TodoListsViewComponent : ViewComponent
    {
        private readonly IToDoListSevices listServices;
        private readonly UserManager<IdentityUser> userManager;

        public TodoListsViewComponent(UserManager<IdentityUser> userManager, IToDoListSevices listServices)
        {
            this.listServices = listServices;
            this.userManager = userManager;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var userId = this.userManager.GetUserId(this.UserClaimsPrincipal);

            var lists = (await this.listServices.GetAllListsAsync()).Where(x => x.UserId == userId);

            return this.View(lists);
        }
    }
}

Todo-aspnetmvc-ui/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>TO DO @ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <nav class="navbar fixed-top bg-primary text-white">
        <div class="container-fluid">
            <div class="row col-12">
                <div class="col-3 navbar">
                    <a href="/" class="nolinktext" title="Main page" style="color: white">
                        <h2>ToDo</h2>
                    </a>
                </div>
                <div class="col-6 navbar">
                    <vc:remainder />
                </div>
                <div class="col-3 navbar-text text-end">
                    @if (User.Identity != null && User.Identity.IsAuthenticated)
                    {
                        <form id="logout" asp-controller="Account" asp-action="Logout" method="POST" title="Log Out">
                            <a class="lgntodo btn btn-outline-secondary" href="javascript: $('#logout').submit()" style="margin-top: 3px;">
                                <i class="fa-solid fa-right-from-bracket"></i>
                            </a>
                        </form>
                    }
                </div>

            </div>
        </div>
    </nav>
    <div style="padding-top: 75px;">
        <div class="row m-1 p-1">
            @{
                string leftClass, rightClass;
                if (@ViewContext.RouteData.Values["Controller"]?.ToString() == "Home")
                {
                    leftClass = "col-12 col-md-3";
                    rightClass = "col-md-9 d-none d-lg-block";
                }
                else
                {
                    leftClass = "col-md-3 d-none d-lg-block";
                    rightClass = "col-12 col-md-9";
                }
            }
            <div class="@leftClass">
                <vc:todo-lists />
            </div>
            <div id="todotasks" class="@rightClass">
                @RenderBody()
            </div>
        </div>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Todo-aspnetmvc-ui/Views/Shared/_Lists.cshtml
@model (IEnumerable<ToDoList> lists, bool hiden)

@foreach (ToDoList list in Model.lists ?? Enumerable.Empty<ToDoList>())
{
    <div class="d-flex justify-content-between">
        <div class="col-11">
            <a class="col-12 listbtn btn" title="@list.Description"
           asp-controller="Task" asp-action="Tasks" asp-route-Id="@list.Id">
                <h5 class="col-12">
                    @list.Title
                </h5>
                <div class="col-12 text-gray truncate-text ">
                    @list.Description
                </div>
                <div class="col-12">
                    @{
                        int taskCount = list.ToDoListTasks.Where(x => x.TaskStatus != Status.Completed).Count();
                    }
                    @Todo_aspnetmvc_ui.Helpers.Helpers.GetStringNumberOf(taskCount,"task","tasks")
                </div>
            </a>
        </div>
        <div class="dropdown d-flex" style="margin-bottom: 6px;">
            <button class="btntodo btn btn-outline-secondary mt-auto">
                <i class="fa-solid fa-ellipsis-vertical"></i>
            </button>
            <div class="dropdown-content">
                <div class="context-menu-btn">
                    @if (Model.hiden)
                    {
                        <a class="btntodo btn" asp-controller="List" asp-action="ChangeVisibility" asp-route-Id="@list.Id" title="Restore '@list.Title' in list">
                            <i class="fa-solid fa-eye"></i>
                        </a>
                    }
                    else
                    {
                        <a class="btntodo btn" asp-controller="List" asp-action="ChangeVisibility" asp-route-Id="@list.Id" title="Hide list '@list.Title'">
                            <i class="fa-solid fa-eye-slash"></i>
                        </a>
                    }
                </div>
                <div class="context-menu-btn">
                    <a class="btntodo btn" asp-controller="List" asp-action="Edit" asp-route-Id="@list.Id" title="Edit list '@list.Title'">
                        <i class="fa-solid fa-pen"></i>
                    </a>
                </div>
                <div class="context-menu-btn">
                    <a class="btntodo btn" asp-controller="List" asp-action="Copy" asp-route-Id="@list.Id" title="Copy list '@list.Title'">
                        <i class="fa-solid fa-clone"></i>
                    </a>
                </div>
                <div class="context-menu-btn">
                    <a class="btntodo btn" asp-controller="List" asp-action="Delete" asp-route-Id="@list.Id" title="Delete list '@list.Title'">
                        <i class="fa-solid fa-trash"></i>
                    </a>
                </div>
            </div>
        </div>
    </div>
}